// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/figma-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";
import { findToken, TOKEN_HELP } from "../figma/token.js";

export const DESCRIPTION =
  "read Figma files, inspect nodes, export assets, and manage comments from the terminal";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

export const COMMAND_ROWS = [
  { command: "file <key-or-url>", summary: "summarize a file: pages, top-level frames, counts" },
  { command: "node <key-or-url> <node-id>", summary: "one node's structure, layout, and style properties" },
  { command: "export <key-or-url> --node <ids>", summary: "render nodes to png/svg/jpg/pdf and download them" },
  { command: "styles <key-or-url>", summary: "published styles in a file library" },
  { command: "components <key-or-url>", summary: "published components in a file library" },
  { command: "comments <key-or-url>", summary: "list comments; --add posts one" },
  { command: "variables <key-or-url>", summary: "local variables / design tokens (Enterprise plans)" },
];

/**
 * Shared body of the home view; `tool` is how commands are written
 * ("figma-axi" live, "npx -y figma-axi" in the static skill).
 */
export function homeBody(tool: string): string {
  const table = emitList("commands", COMMAND_ROWS, ["command", "summary"]);
  const help = helpBlock([
    `${tool} file <key-or-url>  # start here; accepts figma.com URLs or raw file keys`,
    `${tool} node '<url with ?node-id=>'  # node ids also parse straight from URLs`,
    `${tool} export <key> --node <id> --format png --scale 2 --out ./assets`,
    `${tool} <command> --help`,
  ]);
  return [table, help].join("\n");
}

export function renderHome(binPath: string): string {
  const header = `figma-axi: ${collapseHome(binPath)} — ${DESCRIPTION}`;
  const info = findToken();
  const tokenLine = info ? `token: set (${info.source})` : `token: not set — ${TOKEN_HELP}`;
  return [header, tokenLine, homeBody("figma-axi")].join("\n");
}

/** Full tool reference for `figma-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList("commands", COMMAND_ROWS, ["command", "summary"]);
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `figma-axi: ${DESCRIPTION}`,
    `auth: reads FIGMA_TOKEN (personal access token) or ~/.config/figma-axi/config.json`,
    commands,
    flags,
    "examples[3]:",
    "  figma-axi file https://www.figma.com/design/AbCdEf123456/My-Site",
    "  figma-axi node AbCdEf123456 1:2",
    "  figma-axi export AbCdEf123456 --node 1:2 --format png --scale 2",
  ].join("\n");
}

/** The static SKILL.md: home content with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: figma-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# figma-axi",
    "",
    `${DESCRIPTION[0]!.toUpperCase()}${DESCRIPTION.slice(1)} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx — no install needed.`,
    "",
    "Auth: set `FIGMA_TOKEN` to a Figma personal access token (figma.com > settings > security > personal access tokens), or put `{\"token\": \"...\"}` in `~/.config/figma-axi/config.json` (the env var wins).",
    "",
    "Every `<key-or-url>` accepts a raw Figma file key or a full figma.com URL; a URL's `?node-id=` fragment is picked up automatically, and node ids may use either `12:34` or `12-34` form.",
    "",
    "```",
    homeBody("npx -y figma-axi"),
    "```",
    "",
    "Notes:",
    "- `export` downloads the rendered files locally and prints their paths.",
    "- `variables` needs a Figma Enterprise plan; other plans get a clear plan-gated error.",
    "- Large files: `file` fetches only pages + top-level frames by default (`--depth` goes deeper); drill in with `node`.",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
